Display online users in sidebar
IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client pull request #105
Opened 2022-11-08 15:27 UTC by Ju-Gasolina

2022-11-08 20:02 UTC, Zekix27 requested changes

2022-11-08 20:02 UTC, Zekix27 commented on src/components/Sidebar/Sidebar.vue
> +				console.log('true')
pas de log monsieur

2022-11-08 21:52 UTC, DRACOX2500 commented on src/components/Sidebar/Sidebar.vue
> +				console.log('true')
<img src="https://media1.giphy.com/media/eh7W3dJGvRa4FymAPf/giphy.gif"/>

2022-11-08 22:05 UTC, DRACOX2500 requested changes
La même remarque que @Zekix27 + le v-if sur l'élément <i>

2022-11-08 22:05 UTC, DRACOX2500 commented on src/components/Sidebar/Sidebar.vue
> +							<i :class="{ 'ui small icon circle green': userIsOnLine(conversation) }"></i>
Un v-if sur l'élément serait plus approprié

2022-11-08 22:11 UTC, DRACOX2500 commented on src/components/Sidebar/Sidebar.vue
> +							<i :class="{ 'ui small icon circle green': userIsOnLine(conversation) }"></i>
Edit : je me corrige. 
Vu que l'élément est apparemment visible constamment et que tu veux juste mettre la classe "green" en dynamique, fais plutôt comme ça :
```html
<i class="ui small icon circle" :class="{ green: userIsOnLine(conversation) }"></i>
```
comme ça les autres classes restent statiques, donc pas besoin de les recharger

2022-11-09 07:30 UTC, DRACOX2500 approved these changes
RAS

2022-11-09 07:31 UTC, merged

2022-11-09 07:31 UTC, Zekix27 approved these changes