Show unread message (in side bar)
IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client pull request #106
Opened 2022-11-08 19:07 UTC by hedizair

pas confondre avec les message vue dans la conversation

2022-11-08 20:00 UTC, Zekix27 requested changes

2022-11-08 20:00 UTC, Zekix27 commented on src/components/Sidebar/Sidebar.vue
> +
C'est tout vide enlève-moi ça gros dégueulasse et l'espace derrière le "text"

2022-11-08 21:54 UTC, DRACOX2500 commented on src/components/Sidebar/Sidebar.vue
> +
<img src="https://media3.giphy.com/media/dctlg5ReRW4ms/giphy.gif"/>

2022-11-08 21:56 UTC, DRACOX2500 commented on src/components/Sidebar/Sidebar.vue
> +
Après ça va passer par l'ESlint donc pas très grave

2022-11-08 21:59 UTC, DRACOX2500 approved these changes
J'approuve, mais évite d'ajouter des retour à la ligne inutile la prochaine fois

<img src="https://media2.giphy.com/media/mCJkHm7o6vSoAKcLY7/giphy.gif"/>

2022-11-09 07:33 UTC, Zekix27 approved these changes

2022-11-09 15:33 UTC, merged