fix conversation title + green circle in conversation and sidebar
IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client pull request #116
Opened 2022-11-10 08:05 UTC by Ju-Gasolina

2022-11-10 21:42 UTC, Zekix27 requested changes

2022-11-10 21:42 UTC, Zekix27 commented on src/components/Conversation/Conversation.vue
> +		)
On fait ça plusieurs fois, peut-être faire une fonction ?

2022-11-11 00:13 UTC, DRACOX2500 commented on src/components/Conversation/Conversation.vue
> +		)
un getter dans le store

2022-11-11 08:46 UTC, Zekix27 commented on src/components/Conversation/Conversation.vue
> +		)
bien vu l'aveugle

2022-11-11 09:52 UTC, Zekix27 commented on src/components/Conversation/Conversation.vue
> +		)
J'ai essayé de faire un truc, mais je n'arrive pas à utiliser le computed comme les autres getters, vu que j'ai besoin d'un paramètre. C'est du coup considéré comme une action. Je laisserai un d'entre vous tester. Sinon, c'est un peu une fonction de Conversation, mais je ne sais pas si c'est une bonne chose à mettre en place.

2022-11-11 14:03 UTC, DRACOX2500 approved these changes
RAS

2022-11-11 14:04 UTC, merged