Type conversation
IUT-LYON1-VUEJS-GROUPE4/VUE3-Chat-Client pull request #118
Opened 2022-11-10 13:42 UTC by Ju-Gasolina

2022-11-10 22:25 UTC, Zekix27 approved these changes

2022-11-11 00:08 UTC, DRACOX2500 requested changes
Supprime les `console.log()` et le fichier `src/components/Conversation/script.ts` il est vide et inutile

2022-11-11 00:08 UTC, DRACOX2500 commented on src/composables/events.ts
> +			console.log('@conversationTyped')
Pas de log !

2022-11-11 00:08 UTC, DRACOX2500 commented on src/stores/messenger.ts
> +		console.log('conversationTyping0')
PAS DE LOG !

2022-11-11 12:57 UTC, DRACOX2500 approved these changes
RAS

2022-11-11 14:48 UTC, DRACOX2500 approved these changes
RAS

2022-11-11 14:48 UTC, merged